# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yanxuan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for yanxuan
    pod 'Masonry'
    pod 'MJExtension', '~> 3.0.13'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage'
    pod 'Ono'


  target 'yanxuanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'yanxuanUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
